name: CI

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test build Docker images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test build
      id: docker_build_test
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        tags: usatlas/analysisbase-dask:test
        load: true
        push: false
        platforms: linux/amd64

    - name: Image digest
      run: echo ${{ steps.docker_build_test.outputs.digest }}

    - name: List built images
      run: docker images
